### ISSUE TITLE
Ne fonctionne pas chez moi

### ISSUE THREAD

**Issue by gael1980** [kugan49/veolia-custom-component-HACS#1]
Bonjour,

Bravo pour cette intégration.
Le composent n'indique que mes identifiants ne fonctionnent pas avec l'intégration.
Lorsque je teste mes id directement sur le site https://www.service.eau.veolia.fr/ je n'ai pas de pb de connexions.

-->

## Version of the custom_component
J'utilise la V1 dans HASS à jour.
-->

## Configuration

Si besoin (et si vous m'expliquez comment faire, je peux fournir le log)

**Comment by kugan49** [comment]
Merci pour ce retour,

Pour activer les logs :
dans le fichier `configuration.yaml` :

```yaml 
logger:
  default: info
  logs:
    custom_components.veolia: debug
```

J'attends ton retour 😄
