### ISSUE TITLE
Message config was used from VEOLIA, this is deprecated

### ISSUE THREAD

**Issue by Franbour** [kugan49/veolia-custom-component-HACS#61]
## Configuration

```yaml

Add your logs here.

Enregistreur: homeassistant.core
Source: helpers/deprecation.py:222
S'est produit pour la première fois: 10 mai 2025 à 08:28:14 (1 occurrence)
Dernier enregistrement: 10 mai 2025 à 08:28:14

Config was used from veolia, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'veolia' custom integration


```

## Debug log

```text

Add your logs here.

```
